apiVersion: v2
name: peekaboo
description: Self-hosted audio + video baby monitor for your go2rtc cameras
type: application
version: 0.1.0
appVersion: "0.0.1" # x-release-please-version
home: https://github.com/adumat/peekaboo
sources:
  - https://github.com/adumat/peekaboo
keywords:
  - baby-monitor
  - go2rtc
  - rtsp
  - pwa
